/***************************************************************
 * Copyright (C) 2018
 *    Computer Graphics Support Group of 30 Phys-Math Lyceum
 ***************************************************************/

/* FILE NAME   : SHAPES.H
 * PURPOSE     : Ray tracing system.
 *               Box shape class.
 * PROGRAMMER  : DT6.
 * LAST UPDATE : 27.08.2018.
 * NOTE        : None.
 *
 * No part of this file may be changed without agreement of
 * Computer Graphics Support Group of 30 Phys-Math Lyceum
 */

#include "shape.h"
#include "sphere.h"
#include "box.h"
#include "plane.h"
#include "torus.h"
#include "cuadric.h"

/* END OF 'SHAPES.H' FILE */