/***************************************************************
 * Copyright (C) 2018
 *    Computer Graphics Support Group of 30 Phys-Math Lyceum
 ***************************************************************/

/* FILE NAME   : MTH.H
 * PURPOSE     : Ray tracing system.
 *               Math support.
 * PROGRAMMER  : DT6.
 * LAST UPDATE : 12.07.2018.
 * NOTE        : None.
 *
 * No part of this file may be changed without agreement of
 * Computer Graphics Support Group of 30 Phys-Math Lyceum
 */

#ifndef __MTH_H_
#define __MTH_H_

#include "mthdef.h"
#include "vec.h"
#include "matr.h"
#include "camera.h"
#include "ray.h"

#endif // __MTH_H_

/* END OF 'MATH.H' FILE */